### ISSUE TITLE
Checking when parser is done on an infinite stream

### ISSUE THREAD

**Issue by cogmeta** [phorward/phorward#20]
First or all, thank you so much for open sourcing this wonderful library. I have a custom requirement. I have an infinite stream of tokens and the pattern I want to capture is embedded in the stream. It can start anywhere and end anywhere. I am using  pp_parctx_next to update the parser context when the next token in the stream is available. However, I am clueless as how to detect PPPAR_STATE_DONE state after every pp_parctx_next call. Even when the valid statement tokens (generated by the grammar) have been passed the context state is still PPPAR_STATE_NEXT and is changed to PPPAR_STATE_DONE only when pp_parctx_next(ctx, pp_sym_get( grm, 0 ) , NULL) is called. But then I can not add any more tokens. Is there a way to detect PPPAR_STATE_DONE state or way to roll back the parser context ?

**Comment by phorward** [comment]
Hello @cogmeta, and thank your for your request.

I think the problem for your solution is to proxy the call to the parser from your stream. Within this proxy, you first copy the current context into another variable and use it to call [pp_parctx_next()](https://www.phorward-software.com/products/phorward/doc/phorward.html#fn_pp_parctx_next). If the call fails because an invalid token appeared, you throw away the copy and continue in your stream, otherwise you replace the current context by the copy and continue in your stream.

Generally, the solution might look like this one, but it ignores any dynamic memory handling which will be a problem in a real implementation. Unfortunately, copying context structures is currently not implemented into the library, so you have to do it manually (or you write functions for it and contribute them to the project).
```C
/* Original context */
static ppparctx* 	ctx;

/* Proxy function */
BOOLEAN proxy_parser( char* s )
{
	ppparctx		ctxcpy;

	if( !ctx )
		ctx = pp_parctx_create( par );

	/* Copy current context */
	memcpy( &ctxcpy, ctx, sizeof( ppparctx ) );

	/* Call parser with copy */
	if( !pp_parctx_next( &ctxcpy, get_symbol( s ), NULL ) )
		return FALSE; /* Throw copy away! */

	/* Replace original by copy */
	memcpy( ctx, &ctxcpy, sizeof( ppparctx ) );
	return TRUE;
}
```
Maybe this proposal might help you.

**Comment by cogmeta** [comment]
@phorward. Yep, This is what we also thought might work. We will be happy to implement the copy function and contribute it to the project. thank you so much for your help.

**Comment by phorward** [comment]
>  We will be happy to implement the copy function and contribute it to the project. thank you so much for your help.

That would be great :+1: 

Please note, that I've already began to move parts from this project into [UniCCv2](https://github.com/phorward/unicc/tree/v2) because this is the place where future development of a parsing library and tools will resist. The Phorward Library will focus mostly on the dynamic data structures and regular expressions. Feel free to contribute here, I will copy the code to the new project on demand.

**Comment by cogmeta** [comment]
noted. Closing this for now.
